### ISSUE TITLE
Windows Defender Severe Trojan Detection

### ISSUE THREAD

**Issue by MysticalPlane** [0xeb/TheBigPromptLibrary#16]
Windows Defender detected some "severe" trojans in the zip file of the entire repository. 3 in total.

These are the alleged trojans:

Backdoor:Perl/TurtlePerlsh.A!dha

Backdoor:PHP/Perhetshell.B!dha

Trojan:PowerShell/ReverseShell.HNAA!MTB

**Comment by 0xeb** [comment]
Yes, I am not surprised but I assure you, this is a false positive. Keep browsing this repo online, or add a folder exclusion to avoid Windows Defender complaining for nothing.

**Comment by MysticalPlane** [comment]
Got it. Thanks for getting back to me!

________________________________
